### ISSUE TITLE
[Bug] Connecting second city hub fails

### ISSUE THREAD

**Issue by iragm** [Novakasa/brickrail#120]
**Describe the bug**
What is the problem?  I have a clean install of brickrail on Windows 10 and two city hubs with nothing connected.  I can connect the first hub without issue, but the second hub gives a connection error.

**To reproduce**
Given two hubs both flashed with the brickrail firmware using pybricks, open Brickrail.
1. Add train hub
2. Scan for hub
3. First hub appears, click connect, it connects
4. Add train hub
5. Scan for hub
6. Second hub appears, click connect.  It will time out (?) and give a connection error in the GUI
7. The bluetooth window shows this message: sending message: {"key": "connect_error", "hub": "Train 2", "data": ["<class 'Exception'>"]}

**Expected behavior**
Hub should connect

I have not yet had time to dig into this as my development computer does not have BLE capabilities.  But, in `ble_hub.py`, I see:

```
        except Exception:
            self.to_out_queue("connect_error", [repr(Exception)])
```
which I think could be changed to:

```
        except Exception as e:
            self.to_out_queue("connect_error", [e])
```
this would not solve the issue, but would at least give me a clue as to what I am doing wrong.  Or, if you can give me a clue about where to change this code myself, I can do it and report back.

I have ordered a bluetooth dongle for my dev computer which should get here next week and I'll dig into this further unless this is a known thing.

I have noticed some other bugs - things like launching multiple instances of the software, and a few crashes of the BLE window.  I'm not sure the best way to report those, opening a lot of issues for them all seems like it might get noisy.

Anyway, this project has a lot of promise and I really appreciate all the work you've put into it so far!

**Comment by Novakasa** [comment]
Thanks for trying out Brickrail and thanks for the report!

Currently, I am not sure what might be going wrong in your case. Usually the connection timeout happens if the hub is not in "advertising" mode (Advertising == blue LED flashes twice quickly with pauses of ~1 second between) or for some reason the wrong hub name is given.

Which release of brickrail did you try this with? Only official releases are alpha.1 and alpha.2, but you can try a current master build by downloading the brickrail-windows artifact from the github actions page: https://github.com/Novakasa/brickrail/actions/runs/4845313757

Things to keep in mind:
- All hubs should have a different pybricks name (given during flashing of the firmware)
- When "scanning" for the second hub, is the name in the gui that is discovered actually the name of the second hub or did it accidentally discover the first hub again? Usually this is prevented if the first hub is connected (thus not in advertising mode), which you seemed to do, so not sure if this can be the problem. You can also try to turn off the first hub and see if the second hub still can't connect.
- If you try the opposite order of the hubs, does the problem still appear with the second connection or does it already fail with the first connection?
- Are you able to connect to both hubs independently in [Pybricks Code](https://code.pybricks.com/)?
- Did you install the firmware that is distributed with the Brickrail release? (given in firmware/ folder)

I can try to get the exception string to the GUI, but I think this might just be a regular timeout error (meaning the bleak library did not find the device)

**Comment by Novakasa** [comment]
> I have noticed some other bugs - things like launching multiple instances of the software, and a few crashes of the BLE window. I'm not sure the best way to report those, opening a lot of issues for them all seems like it might get noisy.

Feel free to open an issue if you feel it is a bug, if you're unsure we can also talk about it in [Discussions](https://github.com/Novakasa/brickrail/discussions). Currently, multiple instances of brickrail definitely are not supported, as the connection to the BLEServer will not work in that case at the moment.

**Comment by iragm** [comment]
Thank you for the quick reply!

> Usually the connection timeout happens if the hub is not in "advertising" mode (Advertising == blue LED flashes twice quickly with pauses of ~1 second between)

It is in advertising mode.

> or for some reason the wrong hub name is given.

I don't see how this is possible, Brickrail shows the hub name before connect.

> Which version of brickrail did you try this with?

Alpha 2 yesterday, the master build from your link today.  Same behavior in both cases.

> Are your hubs LEGO City hubs?

Yes

> All hubs should have a different pybricks name (given during flashing of the firmware)

Yes.

> When "scanning" for the second hub, is the name in the gui that is discovered actually the name of the second hub or did it accidentally discover the first hub again?

It correctly finds the second hub.

> You can also try to turn off the first hub and see if the second hub still can't connect.

No difference.

>If you try the opposite order of the hubs, does the problem still appear with the second connection or does it already fail with the first connection?

The first connection works regardless of the hub, the second connection does not.  Interestingly, if I connect to the first hub, then use the new "remove" button to remove it, then try to connect again, I cannot connect to the first hub any more.  But, if I restart Brickrail, then I can connect to the first hub (and only the first hub) without issue.  Perhaps something is not getting cleaned up after connect?  Is there any log I can collect that might help?

>Are you able to connect to both hubs independently in [Pybricks Code](https://code.pybricks.com/)?

Yes, this is how I am flashing the Brickrail firmware.  I ran some basic test programs and both hubs seem to work fine, both ports connect to devices and I can control them with pybricks.

>Did you install the firmware that is distributed with the Brickrail release? (given in firmware/ folder) If not, still the connection should technically work fine with normal pybricks firmware, only running a program should produce an error)

Yes, I used cityhub 2730 included with the master build from your link.

**Comment by Novakasa** [comment]
Thanks for the info. I unfortunately still don't see what might be causing this, so the next step would be to test it just using upstream libraries and see if it might be an issue beyond brickrail. If I prepared a python script that requires running it in a python environment that has `pybricksdev` installed, would you be able to do that? If rather not, I can also try to build it into a windows or linux binary for you to test.

**Comment by iragm** [comment]
If it's easy to build a binary, that would be great.

**Comment by iragm** [comment]
Awesome, thanks!

```
C:\Users\user\Downloads\test-two-hubs-windows\test-two-hubs-windows>.\test_two_hubs.exe
scanning for dev1...
dev1: 06:31:0A:DC:B9:CE: Train A
connecting to hub1...
connected to hub1!

scanning for dev2...
dev2: 24:5A:D7:C7:1B:A5: Train B
connecting to hub2!
Traceback (most recent call last):
  File "test_connect_two_hubs.py", line 31, in <module>
  File "asyncio\runners.py", line 44, in run
  File "asyncio\base_events.py", line 649, in run_until_complete
  File "test_connect_two_hubs.py", line 21, in main
  File "pybricksdev\connections\pybricks.py", line 259, in connect
  File "bleak\__init__.py", line 447, in __init__
  File "bleak\backends\winrt\client.py", line 176, in __init__
AttributeError: 'NoneType' object has no attribute 'bluetooth_address'
[16248] Failed to execute script 'test_connect_two_hubs' due to unhandled exception!
```

**Comment by Novakasa** [comment]
Thanks for testing. It indeed does look like an upstream issue to me, but unfortunately a bit beyond my expertise. If you had another PC to test with with, it would be great., I am guessing it must be something about your bluetooth stack/OS version combination that is possibly broken. This probably should be reported to `pybricksdev` or even `bleak`.

If your new bluetooth adapter arrives soon, you could try deactivating the current bluetooth device and try using the new one.

**Comment by iragm** [comment]
Will try that later this week, thanks!

**Comment by iragm** [comment]
I really appreciate all the effort you're putting into this!

Using this latest script I can connect to either device **separately**, no problem.  (Same with all other connection methods I have tried.)  I do have to disconnect the first device to connect to the second one, of course, that is,  I can connect to Train A and disconnect Train A and connect to Train B.  But, I cannot connect to two hubs at the same time in either order:  This script gives the uncaught exception `bleak.exc.BleakError: Could not get GATT services: Unreachable`.

Some googling led me to: https://github.com/hbldh/bleak/issues/740 and https://github.com/hbldh/bleak/issues/1217 and a few other related issues, but there doesn't seem to be a definitive cause or fix.

I also dug out a third City hub, and that shows the same issue, so it does not seem like this is an issue with the Lego hubs.  I can't rule out a bluetooth hardware issue or a Windows thing.  I did install Windows Updates and try a different USB port.  I'll wait for the new USB dongle and see if that helps.  Will update this thread if I dig up any more relevant information.

**Comment by Novakasa** [comment]
I think the `bleak.exc.BleakError: Could not get GATT services: Unreachable` is quite a generic error, I have also seen it from time to time, often when my previous script crashed and disconnects weren't done properly. I think the issue that you only have it when trying to connect 2 devices at the same time is reason enough to report it as a unique issue. The maintainer @dlech for bleak is also a pybricks maintainer, so it wouldn't hurt to mention these are pybricks hubs. If you want I can report for you, but I am fairly certain they'll want [bluetooth packet logs](https://bleak.readthedocs.io/en/latest/troubleshooting.html#capture-bluetooth-traffic) and as such so you might have to follow up on it anyway.

**Comment by Novakasa** [comment]
For completeness, the binaries above have `bleak== 0.20.2` embedded

**Comment by iragm** [comment]
Right now, I feel I need to collect a bit more data before I report this -- I can easily test another computer or two, collect wireshark logs, and try with another dongle.  No sense wasting time if it turns out to be something specific to this one Windows machine.  I should have time to do all of that this weekend and it should clearly establish this as a bug (or not!)

**Comment by Novakasa** [comment]
Also, for now it is not entirely excluded that this might be an issue with packaging bleak as a package using pyinstaller (the way I produce these binaries), though I deem it not very likely to be the problem.

Still, another test could be to run the scripts above using a local python installation (I would recommend miniconda), and then, after activating the standard environment:
```
pip install bleak
python one_of_the_scripts_above.py
```

**Comment by iragm** [comment]
A new bluetooth dongle fixed this.  This is likely to be a software issue that impacts certain bluetooth devices, if someone else runs into this issue I can take the time to try to track down a proper fix, but it is working for me for now with a new dongle.  FWIW, I am using a Plugable USB Bluetooth dongle which works fine with Brickrail on both Windows 10 and Ubuntu.

**Comment by dlech** [comment]
Would you mind sharing the radio info for both the working and not working Bluetooth adapters? We are trying to collect info to be able to provide a list of known problematic and working adapters.

https://github.com/microsoft/busiotools/tree/master/bluetooth/tracing#how-to-collect-bluetooth-radio-information

**Comment by iragm** [comment]
@dlech Sure, happy to.  But running `wget https://github.com/Microsoft/busiotools/raw/master/bluetooth/tracing/GetBluetoothRadioInfo.ps1 -UseBasicParsing | iex` gives the same output for both devices (or indeed, neither device):

```
InstanceId        : USB\VID_0A12&PID_0001\5&2E822EC5&0&3
MAC               : 1A7DDA7113
DriverDescription : Generic Bluetooth Radio
DriverVersion     : 10.0.19041.2728
ErrorRecovery     : None
ScoType           : Unknown

InstanceId        : USB\VID_0A12&PID_0001\5&1280EE4&0&1
MAC               : 1A7DDA7113
DriverDescription : Generic Bluetooth Radio
DriverVersion     : 10.0.19041.2728
ErrorRecovery     : None
ScoType           : Unknown

InstanceId        : USB\VID_2230&PID_0016\00E04C239987
MAC               : 8CAE4CC0341C
DriverDescription : Generic Bluetooth Adapter
DriverVersion     : 10.0.19041.2728
ErrorRecovery     : None
ScoType           : Unknown
```

Am I doing something wrong?

**Comment by dlech** [comment]
The important part is the USB VID and PID.  `0A12:0001` is a Cambridge Silicon Radio chip. `2230:0016` is the Pluggable one. Is it the USB-BT4LE or USB-BT5 version?

Since both use the same driver, I'm guessing the CSR chip is too old and is missing some Bluetooth 4.1 or 4.2 feature that makes a newer adapter work better. Otherwise, I've generally had decent luck with them.

**Comment by iragm** [comment]
The Plugable device is BT5.  I tried again and both give the same exact info, right down to the PID.  Again, the script gives the same info even when there's no dongle plugged into that computer at all, so I am not sure it's working correctly.  Happy to test further.

**Comment by dlech** [comment]
The script is listing all hardware that has been configured, not just what is currently attached. It is listing 3 different radios, two of which are the same one in different USB configurations (same MAC). So that is all of the info I was looking for.
