### ISSUE TITLE
ble-server log paths not setup correctly when server manually connected

### ISSUE THREAD

**Issue by Novakasa** [Novakasa/brickrail#152]
Ah, interesting, the logs show that the first time the server didn't connect properly, but then you probably tried reconnecting it, which worked. But this is probably the reason the log path wasn't setup correctly.

_Originally posted by @Novakasa in https://github.com/Novakasa/brickrail/discussions/150#discussioncomment-6496911_

**Comment by Novakasa** [comment]
@TekyTeky according to your logs in #150 (both brickrail.log) files, there seemed to be an issue connecting to the ble-server at first, but after 30 seconds, it connected successfully. Did you see anything on your end? Did you manually restart the ble-server?

**Comment by TekyTeky** [comment]
The BLE issues sometimes happens and disconnects eg the terminal has a prompt, so I restart the app and it's all good. Today I didn't restart, it reconnected itself before I could check the terminal. So I didn't worry. It is odd indeed that nothing was captured. I was surprised. I'll get the other files later as I am on the GitHub app on my phone. 
In future I will restart the app if BLE fails, to ensure logs are written.

**Comment by TekyTeky** [comment]
Here are all the log files from the Dir.
Seems most were from 08 July

[ble-server.log](https://github.com/Novakasa/brickrail/files/12105325/ble-server.log)
[brickrail.log](https://github.com/Novakasa/brickrail/files/12105326/brickrail.log)
[brickrail_2023-07-08_16.04.29.log](https://github.com/Novakasa/brickrail/files/12105327/brickrail_2023-07-08_16.04.29.log)
[brickrail_2023-07-08_16.10.02.log](https://github.com/Novakasa/brickrail/files/12105328/brickrail_2023-07-08_16.10.02.log)
[brickrail_2023-07-15_10.08.50.log](https://github.com/Novakasa/brickrail/files/12105329/brickrail_2023-07-15_10.08.50.log)
[brickrail_2023-07-20_16.29.56.log](https://github.com/Novakasa/brickrail/files/12105331/brickrail_2023-07-20_16.29.56.log)
![hub_GreenCityTrain_colors_2023-07-08_16 07 21](https://github.com/Novakasa/brickrail/assets/87248517/aed145e7-9a6c-4546-89ef-3a8e7c0c501b)
![hub_GreenCityTrain_colors_2023-07-08_16 09 38](https://github.com/Novakasa/brickrail/assets/87248517/2a53b40d-ab1d-426c-955a-2c491093372c)
[hub_GreenCityTrain_dump_2023-07-08_16.07.21.txt](https://github.com/Novakasa/brickrail/files/12105334/hub_GreenCityTrain_dump_2023-07-08_16.07.21.txt)
[hub_GreenCityTrain_dump_2023-07-08_16.09.38.txt](https://github.com/Novakasa/brickrail/files/12105335/hub_GreenCityTrain_dump_2023-07-08_16.09.38.txt)

**Comment by TekyTeky** [comment]
I just thought I'd start the app, and I got he BLE disc. issue.. The terminal is just waiting like normal.
This is the screen shot and the info and the logs.
![BLE Error](https://github.com/Novakasa/brickrail/assets/87248517/4a39362d-78da-4d53-a374-e85171f2adac)
[brickrail.log](https://github.com/Novakasa/brickrail/files/12105381/brickrail.log)
[brickrail_2023-07-20_21.09.25.log](https://github.com/Novakasa/brickrail/files/12105382/brickrail_2023-07-20_21.09.25.log)


Soooo.. when I went to check the above to see if the BLE folder was with the EXE.. I found the png files etc. in the Download Dir with the exe... are they suppose to be?

Here they are:


![Files](https://github.com/Novakasa/brickrail/assets/87248517/efabf3f2-5c04-46e6-ba54-5ccea0c5c3b1)

![hub_CityTrain3_colors_2023-07-20_16 32 59](https://github.com/Novakasa/brickrail/assets/87248517/5b7ff08d-b83b-4e57-b6ce-4dbb5b48c0a4)
[hub_CityTrain3_dump_2023-07-20_16.32.59.txt](https://github.com/Novakasa/brickrail/files/12105442/hub_CityTrain3_dump_2023-07-20_16.32.59.txt)
![hub_GreenCityTrain_colors_2023-07-20_17 14 07](https://github.com/Novakasa/brickrail/assets/87248517/7a10a089-8263-4538-82a7-90da6d712e13)
[hub_GreenCityTrain_dump_2023-07-20_17.14.07.txt](https://github.com/Novakasa/brickrail/files/12105443/hub_GreenCityTrain_dump_2023-07-20_17.14.07.txt)

**Comment by Novakasa** [comment]
That actually makes sense, if the directory is not configured correctly, it will store the files in the current working directory. Forgot about that.

Thanks, the files are really useful to me. I will probably be able to improve marker detection based on these. Will also increase the timeout timer for ble-server connection, since I am guessing the server just takes a bit longer on your setup to be ready.

**Comment by TekyTeky** [comment]
> That actually makes sense, if the directory is not configured correctly, it will store the files in the current working directory. Forgot about that.

So how should the dir be setup?

**Comment by Novakasa** [comment]
Nothing that the user could fix, I meant: "not configured correctly [by the brickrail-gui process]". So I will need to fix it in the software.

**Comment by Novakasa** [comment]
This is now hopefully fixed in master. Please tell me if you still sometimes get BLEServer connection issues with current master @TekyTeky

**Comment by TekyTeky** [comment]
Also, FYI, I get emailed on every most you make, which I usually read. Using the @TekyTeky highlights my usename in yellow, so I know it is directed to me… so keep doing it if you want me to specifically see something. 😎
