### ISSUE TITLE
[Bug] hubs turning off while connected crashes BLEServer

### ISSUE THREAD

**Issue by TekyTeky** [Novakasa/brickrail#160]
**Describe the bug**
BLE disconnects when a Hub is turned off in Brickrail after batteries go flat/removed

**To reproduce**
1.Battreies go flat in a hub or remove the batteries without turning off the hub first in Brickrail.
2.Turn off the hub in brickrail when you are ready to reconnect the hub (after replacing the batteries)
3.The BLE Disconnects.

**Expected behavior**
Brickrail should still be connected to the other hubs when one is disconnected and turned off in Brickrail.
The hub that disconnected should be set to off in Brickrail automatically when batteries are removed etc.
or when the Hub is turned off in Brickrail, when trying to reconnect, it should turn off, not have a BLE error.

**Screenshots**
![image](https://github.com/Novakasa/brickrail/assets/87248517/60464e7f-e5b9-48b5-8920-99e5c87b3844)

**Logs**
[brickrail.log](https://github.com/Novakasa/brickrail/files/12505376/brickrail.log)
[ble-server_2023-09-03_17.15.09.log](https://github.com/Novakasa/brickrail/files/12505378/ble-server_2023-09-03_17.15.09.log)

**Comment by Novakasa** [comment]
Thanks for reporting! The server definitely shouldn't crash there. Unfortunately the exception is apparently not printed to the ble-server log, so I should work on that.

A hub suddenly losing disconnecting for some reason should probably only trigger emergency stop. For now I recommend disconnecting the hub in brickrail before turning it off.

**Comment by Novakasa** [comment]
Should be fixed now. Unexpected disconnects should now lead to emergency stop with an appropriate error message and you should be able to reconnect the hub if it turns on.
