### ISSUE TITLE
[Bug] Motors with rotation sensors don't work

### ISSUE THREAD

**Issue by iragm** [Novakasa/brickrail#174]
**Describe the bug**
What is the problem?

Several PUP motors, including the very affordable 88008 (Boost M) and the very useful [88013](https://www.bricklink.com/v2/catalog/catalogitem.page?S=88013-1) L-motor give the generic connection error when I attempt to use them.

**To reproduce**
Instead of one of the DCMotor() devices, connect any pybricks Motor() device to your hub.  On running, brickrail goes into emergency stop because the motor isn't connected, but of course there is a motor -- just the "wrong" type.

It looks like this could be addressed in the simplest form with a simple try except block in e.g. `layout_controller.py`:
```
class Switch:
    def __init__(self, port, pulse_duration = 600):
        try:
            self.motor = DCMotor(get_port(port))
        except:
             # also need to import Motor on line 6 above...
             self.motor = Motor(get_port(port)) 
        self.position = _SWITCH_POS_NONE
        self.port = port
        ...
```

This would need to be done in `auto_train.py` and `smart_train.py` too.  But this would leave out some useful stuff, specifically, the L-motor can be set to run at a constant speed regardless of the load.  It might make sense to have some sort of custom class that takes advantage of the rotation sensor when possible, and falls back to the standard DCMotor class when that's not available.   It looks like both auto_train.py and smart_train.py have a TrainMotor() class already that could be used for this.

I'm not set up with a dev environment for this project but I can help with code if needed.  Is there any way that I can use the current release with my own custom pybricks code to test things out?

**Comment by Novakasa** [comment]
Are you seeing this with motors used in switches? Do other motors work fine for you? I am using L-motors and 88008 motors as well as Spike prime motors for switches and they work fine for me. I haven't tested non-train motors on trains yet though. Can you post the logs as found here:
```
Windows: `%APPDATA%/Godot/app_userdata/brickrail-gui/logs`
Linux: `~/.local/share/godot/app_userdata/brickrail-gui/logs`
```

Using the rotation sensor to track a specific speed is definitely something to look at, but I would need to think about how to integrate it with the marker speeds. I am currently using marker speeds to compensate for the fact that a train needs more power to go up a hill and less to go downhill, but if the train has a rotation encoder it will behave differently in these cases.

For experimenting with the python programs, you should be able to just modify the files in the `release/ble-server-<platform>/hub_programs` folder and a restart of brickrail should detect the change and download the new program to the hub automatically (hopefully, please report if this doesn't work)

A dev environment may be setup something like this:
- Download Godot 3.X  and open the project  `brickrail-gui/project.godot`
- Create a python 3.10 environment in `.env/` and activate it (I am using anaconda for this, which might actually be required, not sure there)
- install the dependencies in requirements.txt via `pip install -r ./requirements.txt`

**Comment by iragm** [comment]
Thanks for the help!  So far, I have determined that the pybricks firmware v3.3.0b4-6-g7aca502e bundled with brickrail works fine.  Something about the current version doesn't -- not sure if this is a regression in pybricks or a deliberate change.  I am still in the process of setting up a layout and seeing what works and what doesn't, I will continue to experiment with this over the next week and report back on how things go.

**Comment by Novakasa** [comment]
Confirmed with new pybricks firmware, I will ask upstream whether that is intended.

**Comment by Novakasa** [comment]
This was confirmed to have been unintended behaviour from the beginning, so I added the try except block to account for it. Thanks for reporting!
